# NumPy

In [64]:
import numpy as np

In [13]:
# Create a 1-dimensional NumPy array using np.array()
arr1=np.array([1,2,3,4])

# Create a 2-dimensional NumPy array using np.array()
arr2=np.array([[1,2,3,4],[5,6,7,8]])
#np.ndim(arr2)
# Create a 3-dimensional Numpy array using np.array()
arr3=np.array([[[1,2,3,4],[1,1,1,1]],[[1,1,1,2],[4,3,2,1]]])
np.ndim(arr1),np.ndim(arr2),np.ndim(arr3)



(1, 2, 3)

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [17]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
np.shape(arr1),np.ndim(arr1),arr1.dtype,np.size(arr1)

((4,), 1, dtype('int64'), 4)

In [18]:
# Attributes of 2-dimensional array
np.shape(arr2),np.ndim(arr2),arr2.dtype,np.size(arr2)

((2, 4), 2, dtype('int64'), 8)

In [5]:
# Attributes of 3-dimensional array


In [27]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df=pd.DataFrame(arr2)
df
#3d can't be expressed in the form of dataframe


0  1  2  3
0  1  2  3  4
1  5  6  7  8

In [31]:
arr3


array([[[1, 2, 3, 4],
        [1, 1, 1, 1]],

       [[1, 1, 1, 2],
        [4, 3, 2, 1]]])

In [53]:
arr3_2d=arr3[0,:,:]
arr3_2d.ndim
pd.DataFrame(arr3_2d)

0  1  2  3
0  1  2  3  4
1  1  1  1  1

In [55]:
# Create an array of shape (10, 2) with only ones
np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [56]:
# Create an array of shape (7, 2, 3) of only zeros
np.zeros((7,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [57]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [58]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(0,10,(7,2))

array([[4, 3],
       [3, 3],
       [4, 0],
       [3, 6],
       [5, 7],
       [6, 2],
       [7, 9]], dtype=int32)

In [63]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.rand(3,5) #direct dimension dini

array([[0.6099841 , 0.52760983, 0.39576646, 0.09432436, 0.14000298],
       [0.72124652, 0.57509882, 0.5053325 , 0.84662466, 0.17238283],
       [0.25341951, 0.88670907, 0.69509468, 0.82859895, 0.74412735]])

In [69]:
# Set the random seed to 42
np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0,10,(4,6))
#the random numbers won't change when run again and again

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [71]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
randomArray=np.random.randint(1,10,(3,7))

# Find the unique numbers in the array you just created
np.unique(randomArray) #returns the set of all numbers of which it is made

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [73]:
randomArray

array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2],
       [2, 4, 8, 7, 9, 8, 5]], dtype=int32)

In [74]:
# Find the 0'th index of the latest array you created
randomArray[0,0]

np.int32(7)

In [78]:
# Get the first 2 rows of latest array you created
randomArray[0:2,:]

array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2]], dtype=int32)

In [81]:
# Get the first 2 values of the first 2 rows of the latest array
randomArray[0:2,0:2]

array([[7, 8],
       [4, 2]], dtype=int32)

In [86]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
np.random.seed(9)
arr=np.random.randint(0,10,(3,5))

ones=np.ones((3,5))
arr

array([[5, 6, 8, 6, 1],
       [6, 4, 8, 1, 8],
       [5, 1, 0, 8, 8]], dtype=int32)

In [87]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [88]:
# Add the two arrays together
arr+ones

array([[6., 7., 9., 7., 2.],
       [7., 5., 9., 2., 9.],
       [6., 2., 1., 9., 9.]])

In [90]:
# Create another array of ones of shape (5, 3)
ones2=np.ones((5,3))

In [100]:
# Try add the array of ones and the other most recent array together
#arr+ones2 #shape milena
# for fixing
ones3=ones2.T
np.shape(ones3)
# arr+ones2

(5, 3)

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [103]:
# Create another array of ones of shape (3, 5)
nones=np.ones((3,5))
narr=np.random.randint(0,5,(3,5))

In [22]:
# Subtract the new array of ones from the other most recent array


In [23]:
# Multiply the ones array with the latest array


In [104]:
# Take the latest array to the power of 2 using '**'
narr**2

array([[ 4, 16,  0, 16,  4],
       [ 0,  1,  0,  9,  9],
       [ 9,  1,  0,  0,  1]], dtype=int32)

In [105]:
# Do the same thing with np.square()
np.square(narr)

array([[ 4, 16,  0, 16,  4],
       [ 0,  1,  0,  9,  9],
       [ 9,  1,  0,  0,  1]], dtype=int32)

In [26]:
# Find the mean of the latest array using np.mean()


In [27]:
# Find the maximum of the latest array using np.max()


In [28]:
# Find the minimum of the latest array using np.min()


In [29]:
# Find the standard deviation of the latest array


In [30]:
# Find the variance of the latest array


In [110]:
# Reshape the latest array to (3, 5, 1)
np.reshape(narr,shape=(3,5,1),order='F')

array([[[2],
        [4],
        [0],
        [4],
        [2]],

       [[0],
        [1],
        [0],
        [3],
        [3]],

       [[3],
        [1],
        [0],
        [0],
        [1]]], dtype=int32)

In [32]:
# Transpose the latest array


What does the transpose do?

In [33]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)


In [114]:
# Perform a dot product on the two newest arrays you created
a1=np.array([1,2,3,4])
a2=np.array([1,2,6,4])
np.dot(a1,a2)

np.int64(39)

In [35]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)


In [36]:
# Perform a dot product on the two newest arrays you created


It doesn't work. How would you fix it?

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [38]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [39]:
# Compare the two arrays with '>'


What happens when you compare the arrays with `>`?

In [40]:
# Compare the two arrays with '>='


In [118]:
# Find which elements of the first array are greater than 7
narr=np.random.randint(0,10,(3,5))
narr>7

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False]])

In [117]:
# Which parts of each array are equal? (try using '==')


In [43]:
# Sort one of the arrays you just created in ascending order


In [119]:
# Sort the indexes of one of the arrays you just created
np.sort(narr)

array([[0, 2, 4, 7, 7],
       [2, 2, 2, 3, 6],
       [0, 1, 2, 3, 9]], dtype=int32)

In [120]:
# Find the index with the maximum value in one of the arrays you've created
np.max(narr)

np.int32(9)

In [46]:
# Find the index with the minimum value in one of the arrays you've created


In [122]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
narr
np.max(narr,axis=1) #row ma

array([7, 6, 9], dtype=int32)

In [48]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created


In [123]:
# Create an array of normally distributed random numbers
mean = 0  # Mean of the distribution
std_dev = 1  # Standard deviation
shape = (3, 4)  # Shape of the output array

normal_array = np.random.normal(loc=mean, scale=std_dev, size=shape)
normal_array

array([[-0.15634499, -0.14601579, -0.23135713, -2.19518196],
       [ 0.9571204 ,  0.62843595,  0.42300578, -0.24093167],
       [-0.05923926, -0.22634237, -0.57807466, -1.10458102]])

In [125]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.arange(10,101,10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.